=== HQJaTu/bastinon/xml/user_rule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="user" type="userType"/>
    <xs:complexType name="sourceType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="address" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="serviceType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="zoneType">
        <xs:sequence>
            <xs:element type="sourceType" name="source" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="serviceType" name="service"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="userType">
        <xs:sequence>
            <xs:element type="zoneType" name="zone" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== HQJaTu/bastinon/sample.firewall-rules/users/example.xml
<?xml version="1.0" encoding="utf-8"?>
<user xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/HQJaTu/firewall-updater/master/xml/user_rule.xsd">
    <zone>
        <source address="192.0.2.0/24"/>
        <source address="198.51.100.0/24"/>
        <source address="2001:db8::/32" comment="Sample IPv6-rule"/>
        <source address="203.0.113.15/32" expires="2022-07-01T05:20:00"/>
        <service name="ssh"/>
    </zone>
    <zone>
        <source address="198.51.100.0/24" comment="Small IPv4-block allowed"/>
        <service name="imaps"/>
    </zone>
</user>
